import React from 'react'
import Link from 'next/link'
import CodeBlock from '@/components/Docs/CodeBlock'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'BackBuilder | Documentation',
  description: 'Learn how to call the REST API generated by BackBuilder.',
}

const nav = [
  { href: '#overview', label: 'Overview' },
  { href: '#getting-started', label: 'Getting started' },
  { href: '#base-url', label: 'Base URL & IDs' },
  { href: '#crud', label: 'CRUD endpoints' },
  { href: '#querying', label: 'Filtering & pagination' },
  { href: '#field-types', label: 'Field types' },
  { href: '#auth-endpoints', label: 'Register & login' },
  { href: '#protecting', label: 'Protecting endpoints' },
  { href: '#origins', label: 'Restricting origins' },
  { href: '#errors', label: 'Responses & errors' },
]

function Section({ id, title, eyebrow, children }: { id: string; title: React.ReactNode; eyebrow?: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-24 py-10 border-b border-line last:border-0">
      {eyebrow && <span className="section-eyebrow">{eyebrow}</span>}
      <h2 className="mt-3 text-2xl md:text-3xl font-bold text-ink">{title}</h2>
      <div className="mt-4 space-y-4 text-[15px] leading-relaxed text-slate-700">
        {children}
      </div>
    </section>
  )
}

function Th({ children }: { children: React.ReactNode }) {
  return <th className="text-left text-xs font-semibold uppercase tracking-wide text-muted px-3 py-2 border-b border-line">{children}</th>
}
function Td({ children }: { children: React.ReactNode }) {
  return <td className="px-3 py-2 border-b border-line align-top">{children}</td>
}

function Method({ verb, color }: { verb: string; color: string }) {
  return <span className={`inline-block text-[11px] font-bold px-2 py-0.5 rounded ${color}`}>{verb}</span>
}

export default function DocsPage() {
  return (
    <div className="max-w-[85rem] mx-auto px-4 sm:px-6 lg:px-8">
      <div className="grid lg:grid-cols-[220px_1fr] gap-10 py-10">
        {/* Sidebar TOC */}
        <aside className="hidden lg:block">
          <div className="sticky top-24">
            <p className="text-xs font-semibold uppercase tracking-wide text-muted mb-3">On this page</p>
            <nav className="space-y-1 text-sm">
              {nav.map((n) => (
                <a key={n.href} href={n.href} className="block px-2 py-1.5 rounded-md text-slate-600 hover:text-primary hover:bg-primary-light/60 transition-colors">
                  {n.label}
                </a>
              ))}
            </nav>
            <Link href="/console" className="mt-6 inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline">
              Go to your console →
            </Link>
          </div>
        </aside>

        {/* Content */}
        <div>
          <div className="pb-8">
            <span className="section-eyebrow">Documentation</span>
            <h1 className="mt-3 text-3xl md:text-5xl font-extrabold text-ink">Build with the BackBuilder API</h1>
            <p className="mt-4 text-lg text-muted max-w-2xl">
              Every table you create in the Console is automatically exposed as a REST endpoint. This page shows you exactly how to call it — no backend code required.
            </p>
          </div>

          <Section id="overview" title="Overview">
            <p>
              BackBuilder turns a database schema you design visually into a hosted REST API. Each <strong>project</strong> can contain many <strong>endpoints</strong> (think: database tables). Every endpoint automatically supports:
            </p>
            <ul className="list-disc pl-5 space-y-1">
              <li><Method verb="GET" color="bg-primary-light text-primary" /> — read one record, many records, or filter/paginate results</li>
              <li><Method verb="POST" color="bg-orange/20 text-orange" /> — create a new record</li>
              <li><Method verb="PUT" color="bg-sky-100 text-sky-700" /> — update an existing record by ID</li>
              <li><Method verb="DELETE" color="bg-red-100 text-red-600" /> — delete a record by ID</li>
            </ul>
            <p>
              Endpoints created as a <strong>Users endpoint</strong> additionally expose <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">register</code> and <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">login</code> actions so you can build authentication straight into your app.
            </p>
          </Section>

          <Section id="getting-started" eyebrow="Step 1" title="Find your endpoint URL">
            <p>
              Every endpoint page in the Console shows a ready-to-copy URL and live request examples for that specific endpoint. To get there:
            </p>
            <ol className="list-decimal pl-5 space-y-1">
              <li>Open your <Link href="/console" className="text-primary hover:underline">Console</Link> and select a project.</li>
              <li>Click into any endpoint under that project.</li>
              <li>Copy the URL shown at the top of the page — it already has your user, project and endpoint IDs filled in.</li>
            </ol>
          </Section>

          <Section id="base-url" eyebrow="Step 2" title="Understanding the URL structure">
            <p>Every request to a data endpoint follows the same shape:</p>
            <CodeBlock
              lang="text"
              code={`{BASE_URL}/api/user/{user_id}/{project_id}/{endpoint_name}`}
            />
            <table className="w-full text-sm">
              <thead><tr><Th>Segment</Th><Th>Description</Th></tr></thead>
              <tbody>
                <tr><Td><code>user_id</code></Td><Td>Your BackBuilder account ID.</Td></tr>
                <tr><Td><code>project_id</code></Td><Td>The ID of the project this endpoint belongs to.</Td></tr>
                <tr><Td><code>endpoint_name</code></Td><Td>The name you gave the endpoint when you created it.</Td></tr>
              </tbody>
            </table>
            <p className="text-sm text-muted">You never have to build this URL by hand — copy it from the endpoint page in the Console.</p>
          </Section>

          <Section id="crud" title="CRUD endpoints">
            <p><Method verb="GET" color="bg-primary-light text-primary" /> Get every record in the table:</p>
            <CodeBlock
              title="Get all records"
              code={`fetch('{ENDPOINT_URL}')
  .then(res => res.json())
  .then(data => console.log(data))`}
            />

            <p><Method verb="GET" color="bg-primary-light text-primary" /> Get a single record by its ID — append the ID to the URL:</p>
            <CodeBlock
              title="Get one record"
              code={`fetch('{ENDPOINT_URL}/12')
  .then(res => res.json())
  .then(data => console.log(data))`}
            />

            <p><Method verb="POST" color="bg-orange/20 text-orange" /> Create a new record. The request body must match the fields you defined for this endpoint:</p>
            <CodeBlock
              title="Create a record"
              code={`fetch('{ENDPOINT_URL}', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    name: 'Air Jordan 1',
    price: 129.99
  })
})
  .then(res => res.json())
  .then(data => console.log(data))`}
            />

            <p><Method verb="PUT" color="bg-sky-100 text-sky-700" /> Update a record — the ID goes in the URL, changed fields go in the body:</p>
            <CodeBlock
              title="Update a record"
              code={`fetch('{ENDPOINT_URL}/12', {
  method: 'PUT',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({ price: 109.99 })
})
  .then(res => res.json())
  .then(data => console.log(data))`}
            />

            <p><Method verb="DELETE" color="bg-red-100 text-red-600" /> Delete a record by ID:</p>
            <CodeBlock
              title="Delete a record"
              code={`fetch('{ENDPOINT_URL}/12', { method: 'DELETE' })
  .then(res => res.json())
  .then(data => console.log(data))`}
            />
          </Section>

          <Section id="querying" title="Filtering, ranges & pagination">
            <p>Filter records by any field using ordinary query parameters — each pair is combined with <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">AND</code>:</p>
            <CodeBlock
              title="Filter by fields"
              lang="text"
              code={`GET {ENDPOINT_URL}?name=sharif&age=22`}
            />
            <p>Slice results by position by adding a <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">start-end</code> range segment after the endpoint name. This can be combined with filters:</p>
            <CodeBlock
              title="Range of records"
              lang="text"
              code={`GET {ENDPOINT_URL}/0-10
GET {ENDPOINT_URL}/0-10?category=shoes`}
            />
          </Section>

          <Section id="field-types" title="Supported field types">
            <p>When designing an endpoint&apos;s schema in the Console, each field can be one of:</p>
            <div className="flex flex-wrap gap-2">
              {['string', 'integer', 'float', 'boolean', 'null'].map((t) => (
                <span key={t} className="text-xs font-mono bg-slate-100 text-ink px-2.5 py-1 rounded-md border border-line">{t}</span>
              ))}
            </div>
            <p className="text-sm text-muted">Fields marked <strong>required</strong> are validated on every <code className="bg-slate-100 px-1 rounded">POST</code> request — requests missing a required field are rejected with a 4xx response.</p>
          </Section>

          <Section id="auth-endpoints" title="Register & login endpoints">
            <p>
              If you created an endpoint as a <strong>Users endpoint</strong>, it exposes <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">register</code> and <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">login</code> actions instead of open CRUD, at:
            </p>
            <CodeBlock
              lang="text"
              code={`{BASE_URL}/api/account/{user_id}/{project_id}/{endpoint_name}/register
{BASE_URL}/api/account/{user_id}/{project_id}/{endpoint_name}/login`}
            />
            <p>Both are <Method verb="POST" color="bg-orange/20 text-orange" /> requests. A users endpoint must define at least a <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">username</code>/<code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">email</code> field and a <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">password</code> field.</p>
            <CodeBlock
              title="Register a user"
              code={`fetch('{ENDPOINT_URL}/register', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    email: 'jane@example.com',
    password: 'super-secret'
  })
})
  .then(res => res.json())
  .then(data => console.log(data))`}
            />
            <CodeBlock
              title="Log in"
              code={`fetch('{ENDPOINT_URL}/login', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    email: 'jane@example.com',
    password: 'super-secret'
  })
})
  .then(res => res.json())
  .then(({ token }) => {
    // store this token and send it back as
    // Authorization: Bearer <token> on protected requests
  })`}
            />
            <p className="text-sm text-muted">A successful login returns a JSON Web Token that expires after 1 day.</p>
          </Section>

          <Section id="protecting" title="Protecting endpoints with auth">
            <p>
              When creating or editing an endpoint, you can choose which HTTP methods require authentication. For those methods, callers must send the token returned by <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">login</code> as a bearer token:
            </p>
            <CodeBlock
              title="Authenticated request"
              code={`fetch('{ENDPOINT_URL}', {
  headers: {
    Authorization: 'Bearer ' + token
  }
})
  .then(res => res.json())
  .then(data => console.log(data))`}
            />
            <p className="text-sm text-muted">Requests to a protected method without a valid, unexpired token receive a <code className="bg-slate-100 px-1 rounded">401 Unauthorized</code> response.</p>
          </Section>

          <Section id="origins" title="Restricting allowed origins">
            <p>
              By default your API accepts requests from anywhere. If you want to lock it down, open a project&apos;s page in the Console and add one or more domains under <strong>Specify your Domain</strong> (for example <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">https://myapp.com</code>). Once at least one domain is added, browser requests are only accepted from an origin on that list. Server-to-server requests, which don&apos;t send a browser <code className="bg-slate-100 px-1 rounded">Origin</code> header, are unaffected.
            </p>
          </Section>

          <Section id="errors" title="Response format & errors">
            <p>Every response is JSON and includes a <code className="text-sm bg-slate-100 px-1.5 py-0.5 rounded">success</code> flag:</p>
            <CodeBlock
              title="Success"
              lang="json"
              code={`{
  "success": true,
  "message": "Data get successfully",
  "data": [ ... ]
}`}
            />
            <CodeBlock
              title="Error"
              lang="json"
              code={`{
  "success": false,
  "message": "Endpoint not found"
}`}
            />
            <table className="w-full text-sm">
              <thead><tr><Th>Status</Th><Th>Meaning</Th></tr></thead>
              <tbody>
                <tr><Td>200</Td><Td>Request succeeded.</Td></tr>
                <tr><Td>401</Td><Td>Missing/invalid auth token, or origin not allowed.</Td></tr>
                <tr><Td>404</Td><Td>User, project, endpoint or record not found.</Td></tr>
                <tr><Td>500</Td><Td>Unexpected server error.</Td></tr>
              </tbody>
            </table>
          </Section>

          <div className="py-10">
            <div className="rounded-2xl bg-primary-light p-8 text-center">
              <h3 className="text-xl font-bold text-ink">Ready to try it yourself?</h3>
              <p className="mt-2 text-muted">Create a project in the Console and get a live endpoint URL in under a minute.</p>
              <Link href="/console" className="mt-5 inline-flex items-center gap-2 px-5 py-3 rounded-lg bg-primary text-white font-semibold hover:bg-primary-dark transition-colors">
                Go to Console
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
