import React from 'react'
import example from '@/assets/images/exmaples/example.png'
import ecommerce from '@/assets/images/exmaples/ecommerce.png'
import Image from 'next/image'

const projects = [
  { href: 'https://back-builder-to-do-list.vercel.app/', img: example, title: 'A To-do List built with BackBuilder' },
  { href: 'https://shoe-shop-backbuilder.vercel.app/', img: ecommerce, title: 'Shoe Shop built with BackBuilder' },
]

export default function Expamples() {
  return (
    <section className="max-w-[85rem] px-4 py-14 sm:px-6 lg:px-8 mx-auto">
      <div className="max-w-2xl mx-auto text-center mb-10">
        <span className="section-eyebrow">Showcase</span>
        <h2 className="mt-3 text-2xl md:text-4xl font-bold text-ink">
          Real projects built on <span className="text-orange">BackBuilder</span>
        </h2>
        <p className="mt-2 text-muted">These live projects run entirely on APIs generated by BackBuilder.</p>
      </div>

      <div className="grid sm:grid-cols-2 gap-8">
        {projects.map((p) => (
          <a key={p.href} href={p.href} target="_blank" rel="noreferrer" className="group block">
            <div className="rounded-2xl overflow-hidden border border-line shadow-card">
              <Image className="w-full h-64 object-cover group-hover:scale-105 transition-transform duration-500" src={p.img} alt={p.title} width={2000} height={2000} />
            </div>
            <h3 className="mt-4 text-lg text-center font-medium text-ink group-hover:text-primary transition-colors">{p.title}</h3>
          </a>
        ))}
      </div>
    </section>
  )
}
